In [2]:
import numpy as np

In [4]:
lista = [1,4,9,16]
#operación normal
print(np.sqrt(1))
print(np.sqrt(4))
print(np.sqrt(9))
print(np.sqrt(16))

1.0
2.0
3.0
4.0


In [5]:
np.sqrt(lista)

array([1., 2., 3., 4.])

In [ ]:
import numba #transforma operaciones normales en operaciones vectorizadas

In [9]:
data = np.array([[1,3,5],[2,4,6]])
data_aux = np.array([[8,9,10],[7,8,9]])
print(data)
print(data_aux)

[[1 3 5]
 [2 4 6]]
[[ 8  9 10]
 [ 7  8  9]]


In [10]:
data * 10

array([[10, 30, 50],
       [20, 40, 60]])

In [12]:
data + 5

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [13]:
data - 3

array([[-2,  0,  2],
       [-1,  1,  3]])

In [11]:
#no es una operación matricial, es una operación de elemento por elemento
data * data_aux

array([[ 8, 27, 50],
       [14, 32, 54]])

In [14]:
#Tamaño de la matriz
data.shape

(2, 3)

In [15]:
data_aux.shape

(2, 3)

In [16]:
#Tipo de dato
data.dtype

dtype('int64')

In [19]:
dataX = np.array([["uno",3,5],[2,4,6]])

In [20]:
dataX.dtype

dtype('<U3')

In [23]:
data1 = [6,7,8,9,0,4]
arr1 = np.array(data1)
arr1

array([6, 7, 8, 9, 0, 4])

In [26]:
arra =np.array(data1).reshape(2,3)
arra

array([[6, 7, 8],
       [9, 0, 4]])

In [27]:
data_aux2.ndim

NameError: name 'data_aux2' is not defined

In [31]:
#Podemos cambiar el tipo de los datos que entra dentro de este vector de ceros
cero = np.zeros(4, dtype=int)
cero

array([0, 0, 0, 0])

In [32]:
ca = np.zeros((3,6))

In [33]:
ca.shape
ca

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [38]:
np.empty((2,2))

array([[1., 2.],
       [3., 4.]])

In [39]:
np.ones((2,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [40]:
np.eye(5) #devuelve la matriz identidad

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr_slice snssd