In [1]:
import numpy as np

In [24]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])

In [25]:
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [26]:
cond = np.array([True, False, True, True, False])

In [27]:
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]

In [6]:
result

[1.1, 2.2, 1.3, 1.4, 2.5]

In [10]:
x = True
if x != True:
    print('OK')
else:
    print('No Ok')

No Ok


In [9]:
if not x:
    print('OK')
else:
    print('No Ok')

No Ok


In [36]:
result = np.where(cond, print(xarr), yarr)

[1.1 1.2 1.3 1.4 1.5]


In [37]:
xarr

array([1.1, 1.2, 1.3, 1.4, 1.5])

In [38]:
result

array([None, 2.2, None, None, 2.5], dtype=object)

In [30]:
result = np.where(cond, xarr**2, yarr)

In [31]:
result

array([1.21, 2.2 , 1.69, 1.96, 2.5 ])

In [17]:
arr = np.random.randn(4, 4)

In [18]:
arr

array([[ 1.72708491, -0.85558643, -0.03773719,  3.12192765],
       [-0.4469586 ,  0.52414897, -0.57502313,  0.952641  ],
       [-0.50430454, -1.70992773, -0.79444413,  0.71615214],
       [-0.1154591 , -2.30735125, -0.59358454,  1.37482821]])

In [19]:
np.where(arr > 0, 2, -2)

array([[ 2, -2, -2,  2],
       [-2,  2, -2,  2],
       [-2, -2, -2,  2],
       [-2, -2, -2,  2]])

In [21]:
np.where(xarr < 1.3, 'esto es poco', xarr)

array(['esto es poco', 'esto es poco', '1.3', '1.4', '1.5'], dtype='<U32')

In [22]:
np.where(arr > 0, 2, arr)

array([[ 2.        , -0.85558643, -0.03773719,  2.        ],
       [-0.4469586 ,  2.        , -0.57502313,  2.        ],
       [-0.50430454, -1.70992773, -0.79444413,  2.        ],
       [-0.1154591 , -2.30735125, -0.59358454,  2.        ]])

In [23]:
result = []
for i in range(n):
    if cond1[i] and cond2[i]:
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)

NameError: name 'n' is not defined

In [90]:
norm = np.random.randn(5, 6)

In [50]:
norm.mean()

0.07017597490302381

In [57]:
norm.sum(axis=0)

array([ 1.07868306e+00, -1.00327238e-01,  1.78620620e+00,  2.03586530e+00,
        8.45873641e-01, -1.53060728e-01,  1.09286592e+00,  1.31266946e+00,
        1.87822100e+00,  1.06527583e+00,  7.98231093e-01, -2.23866456e+00,
        3.12148367e+00,  3.47242567e+00,  1.50655090e-01, -2.34584667e-01,
       -6.93886671e-01,  6.73261149e-01, -1.21416105e-01,  3.66585477e-01,
       -2.25270293e+00,  9.18642421e-01, -2.14410681e+00,  2.49376761e-01,
        5.13444413e-01,  3.49550978e+00, -2.53533791e+00,  3.31847103e-01,
       -1.67010270e+00,  5.50482058e-01,  3.65809389e+00, -2.47413123e-03,
        1.26921686e+00, -2.70666982e+00, -7.34170322e-01, -5.01553632e+00,
       -1.69791472e+00, -2.42926699e+00,  2.80967066e-01,  2.36974107e+00,
        6.09820106e+00,  8.75778849e-01, -3.22180387e+00,  2.81313143e+00,
       -4.07126683e+00, -2.71998793e+00,  2.84632415e+00,  1.46348725e+00,
        1.56592833e+00,  3.30879994e+00])

In [52]:
norm

array([[ 0.21382157, -2.34270514,  0.86145322, -0.05688237, -0.79674905,
         0.40522192, -0.17605601, -1.27264903, -0.76597134,  0.42218277,
        -0.63589862, -0.08803525,  1.37792814,  3.31105413,  0.22162584,
        -0.64409101,  0.29511746,  0.60758674, -1.74075901,  1.32808026,
        -3.04717841,  0.77785588, -0.24320103, -0.0633551 ,  0.0752935 ,
         0.72941045, -0.42436395,  1.40968465, -1.68929856,  2.29795521,
         2.72236454,  1.31049266, -0.31879674, -1.57675285, -0.52775445,
        -1.36349938,  1.61999731, -0.36500017, -0.83009753, -0.07295509,
        -0.42934301, -0.21641007, -0.35667202,  1.14660807, -1.11558409,
         0.40416618,  0.35238712,  0.43562356, -0.93030588, -0.27188945],
       [ 1.04568203,  1.14322525, -2.16563555, -0.01659959, -0.36658591,
        -1.07545006,  1.53221869, -0.65600913,  0.57245496, -0.20701583,
        -0.24180477, -0.70544409,  1.23928183,  1.16496928,  1.10398756,
        -1.61021093,  0.65586848,  0.724948  ,  0.

In [48]:
sum([ 1.04642283, -1.00000555,  0.32953287, -0.74026322]) / 4

-0.0910782675

In [60]:
np.where(norm<0, 0, np.sum(norm))

array([[17.54399373,  0.        , 17.54399373,  0.        ,  0.        ,
        17.54399373,  0.        ,  0.        ,  0.        , 17.54399373,
         0.        ,  0.        , 17.54399373, 17.54399373, 17.54399373,
         0.        , 17.54399373, 17.54399373,  0.        , 17.54399373,
         0.        , 17.54399373,  0.        ,  0.        , 17.54399373,
        17.54399373,  0.        , 17.54399373,  0.        , 17.54399373,
        17.54399373, 17.54399373,  0.        ,  0.        ,  0.        ,
         0.        , 17.54399373,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        , 17.54399373,  0.        ,
        17.54399373, 17.54399373, 17.54399373,  0.        ,  0.        ],
       [17.54399373, 17.54399373,  0.        ,  0.        ,  0.        ,
         0.        , 17.54399373,  0.        , 17.54399373,  0.        ,
         0.        ,  0.        , 17.54399373, 17.54399373, 17.54399373,
         0.        , 17.54399373, 17.54399373, 17.

In [68]:
arr = np.array([[3, 1, 2], [1, 1, 1], [1, 1, 1]])

In [69]:
arr

array([[3, 1, 2],
       [1, 1, 1],
       [1, 1, 1]])

In [72]:
arr.cumsum(axis=0)

array([[3, 1, 2],
       [4, 2, 3],
       [5, 3, 4]])

In [76]:
arr.cumprod()

array([3, 3, 6, 6, 6, 6, 6, 6, 6])

In [80]:
norm.var(axis=0)

array([0.96128944, 1.44341804, 1.70729759, 1.24889302, 0.49270128,
       1.16209399, 0.66147343, 1.39618086, 1.68531764, 0.12764326,
       0.52562298, 0.29597347, 1.10001964, 2.12099448, 0.73078987,
       0.93273559, 0.38315799, 0.23888171, 1.06545783, 1.21417865,
       1.79129828, 0.49931918, 0.16313345, 1.43203113, 0.75191998,
       0.57223546, 0.05920949, 0.63074734, 0.81631979, 1.34288701,
       1.72021595, 0.90247046, 0.81115788, 0.79853935, 0.66095242,
       0.39188418, 1.49225671, 0.40121246, 0.27016462, 0.46015382,
       1.36080974, 2.13161446, 0.38836321, 0.22894862, 0.13832484,
       1.04713915, 0.17920951, 0.6061646 , 0.84748491, 0.30024656])

In [81]:
(arr > 0)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [83]:
arr = np.random.randn(100)

In [87]:
(arr < 0).sum()

52

In [88]:
norm.sort()

In [89]:
norm

array([[-3.04717841, -2.34270514, -1.74075901, -1.68929856, -1.57675285,
        -1.36349938, -1.27264903, -1.11558409, -0.93030588, -0.83009753,
        -0.79674905, -0.76597134, -0.64409101, -0.63589862, -0.52775445,
        -0.42934301, -0.42436395, -0.36500017, -0.35667202, -0.31879674,
        -0.27188945, -0.24320103, -0.21641007, -0.17605601, -0.08803525,
        -0.07295509, -0.0633551 , -0.05688237,  0.0752935 ,  0.21382157,
         0.22162584,  0.29511746,  0.35238712,  0.40416618,  0.40522192,
         0.42218277,  0.43562356,  0.60758674,  0.72941045,  0.77785588,
         0.86145322,  1.14660807,  1.31049266,  1.32808026,  1.37792814,
         1.40968465,  1.61999731,  2.29795521,  2.72236454,  3.31105413],
       [-2.16563555, -2.08828535, -1.87687405, -1.61021093, -1.5633422 ,
        -1.37825846, -1.19771035, -1.07545006, -1.05846563, -0.99207126,
        -0.96086755, -0.79967674, -0.74223067, -0.70544409, -0.67238446,
        -0.65600913, -0.61631323, -0.36658591, -0.

In [91]:
norm

array([[-0.70403487, -0.19009587,  0.68535959, -0.21383815,  0.23685318,
        -1.00607023],
       [-0.71733977,  0.30454021, -0.05321593,  1.41207044, -0.5916277 ,
        -0.62633377],
       [-0.63616972, -0.54465363,  1.58992505,  0.84515285,  0.631333  ,
        -0.28093637],
       [-0.77734697, -0.0377983 ,  0.08745318, -0.34177462,  1.86872881,
        -0.85898455],
       [ 0.02781892, -0.73263864,  0.53365092, -0.02717418,  0.37667404,
         0.35788112]])

In [92]:
norm.sort(axis=0)

In [93]:
norm

array([[-0.77734697, -0.73263864, -0.05321593, -0.34177462, -0.5916277 ,
        -1.00607023],
       [-0.71733977, -0.54465363,  0.08745318, -0.21383815,  0.23685318,
        -0.85898455],
       [-0.70403487, -0.19009587,  0.53365092, -0.02717418,  0.37667404,
        -0.62633377],
       [-0.63616972, -0.0377983 ,  0.68535959,  0.84515285,  0.631333  ,
        -0.28093637],
       [ 0.02781892,  0.30454021,  1.58992505,  1.41207044,  1.86872881,
         0.35788112]])

In [94]:
x = np.array(['Maria', 'Jesús', 'Jesús', 'Antonio', 'Marta'])

In [97]:
np.unique(x)

array(['Antonio', 'Jesús', 'Maria', 'Marta'], dtype='<U7')

In [ ]:
set(list())

In [98]:
arr = np.arange(10)

In [101]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
np.save('array', arr)

In [100]:
np.load('array.npy')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
X = np.random.randn(5, 5)

In [105]:
X

array([[ 0.52609714,  1.18608934, -0.22099199,  1.71704318, -1.11412523],
       [ 0.34386685,  0.32338095,  1.49042441,  0.56943462,  0.80135798],
       [ 0.13563391, -1.72556068, -0.10233309,  0.41745962, -1.30389638],
       [-0.13967672, -0.38495163, -1.29799624, -0.63151884,  1.25821593],
       [-0.06622957, -0.61025695, -0.37878439,  0.23616311,  1.36958296]])

In [106]:
np.linalg.det(X)

-3.4722628119399337

In [109]:
np.linalg.inv(X) * X

array([[ 3.10199841e-01,  2.80994174e+00, -2.50451151e-01,
         5.81861913e+00,  3.27638424e+00],
       [ 4.84257692e-02, -3.39958220e-02, -6.36424254e-01,
        -3.40535790e-02, -1.40653652e-01],
       [-3.42481008e-02, -3.78173203e-01,  4.95576294e-03,
        -2.05985432e-01, -9.59134927e-02],
       [-3.59104480e-02,  1.87573508e-01,  1.81054475e-01,
         6.02052378e-01,  1.55675148e+00],
       [ 1.51697680e-03, -1.29590983e-01,  4.72735879e-02,
         3.90015294e-02,  4.33788174e-01]])

In [110]:
X.dot(np.linalg.inv(X))

array([[ 1.00000000e+00,  2.82379048e-17,  4.97057258e-17,
         4.66024737e-17, -7.42820738e-17],
       [-2.18946183e-17,  1.00000000e+00,  1.70315034e-17,
         7.06892205e-17, -9.52412829e-17],
       [-4.75095168e-17,  8.17022066e-17,  1.00000000e+00,
         7.56767272e-17, -8.04688516e-17],
       [ 1.05621413e-17,  4.13929211e-17, -1.68112090e-17,
         1.00000000e+00,  3.30201591e-17],
       [-3.80098713e-17, -3.45341183e-18, -3.04477394e-17,
         8.39287040e-17,  1.00000000e+00]])

In [155]:
np.random.seed(23)
np.random.randint(17)

6

In [117]:
np.random.seed(1234)

In [164]:
random.randint(0, 1)

1

In [159]:
import random
position = 0
walk = [position]
steps = 1000
for i in range(steps):
    step = 1 if random.randint(0, 1) else -1
    position += step
    walk.append(position)

In [160]:
walk

[0,
 1,
 0,
 -1,
 -2,
 -1,
 0,
 -1,
 -2,
 -1,
 0,
 -1,
 0,
 -1,
 0,
 -1,
 -2,
 -1,
 0,
 -1,
 -2,
 -1,
 0,
 1,
 0,
 -1,
 0,
 1,
 2,
 3,
 4,
 5,
 6,
 5,
 6,
 7,
 8,
 7,
 6,
 7,
 6,
 7,
 6,
 7,
 6,
 7,
 8,
 7,
 8,
 9,
 8,
 9,
 10,
 11,
 12,
 11,
 10,
 9,
 8,
 9,
 8,
 7,
 8,
 9,
 10,
 11,
 10,
 9,
 10,
 9,
 10,
 11,
 10,
 11,
 12,
 11,
 12,
 11,
 12,
 11,
 10,
 11,
 12,
 11,
 12,
 11,
 12,
 13,
 12,
 13,
 12,
 11,
 12,
 13,
 14,
 15,
 14,
 13,
 12,
 11,
 12,
 13,
 12,
 13,
 12,
 13,
 12,
 11,
 10,
 11,
 10,
 9,
 8,
 7,
 6,
 5,
 6,
 5,
 4,
 5,
 6,
 7,
 8,
 9,
 8,
 7,
 8,
 9,
 10,
 11,
 10,
 11,
 10,
 11,
 12,
 11,
 10,
 11,
 10,
 9,
 10,
 11,
 12,
 11,
 12,
 11,
 12,
 11,
 12,
 13,
 14,
 13,
 12,
 11,
 12,
 11,
 10,
 11,
 10,
 9,
 10,
 11,
 10,
 9,
 8,
 9,
 8,
 7,
 8,
 7,
 6,
 7,
 6,
 7,
 8,
 7,
 8,
 9,
 8,
 7,
 8,
 9,
 8,
 7,
 6,
 7,
 8,
 9,
 8,
 9,
 8,
 7,
 6,
 7,
 8,
 9,
 8,
 7,
 6,
 7,
 8,
 9,
 8,
 9,
 10,
 11,
 10,
 11,
 12,
 11,
 10,
 11,
 10,
 11,
 10,
 11,
 12,
 13,
 12,
 13,
 12,
 

In [165]:
walk[-1]

36

In [171]:
6*7*8

336

336

In [174]:
arr = np.arange(15)

In [175]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [183]:
ej = arr.reshape((-1, 3))

In [184]:
ej.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [188]:
np.eye(4).ravel()

array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.])

In [190]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

In [192]:
arr1.shape

(2, 3)

In [193]:
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

In [195]:
arr2.shape

(2, 3)

In [197]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [198]:
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [196]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [200]:
np.concatenate([arr1, arr], axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [201]:
arr.shape

(15,)

In [205]:
np.random.seed(1234)
arr = np.random.randn(5, 2)

In [206]:
arr

array([[ 0.47143516, -1.19097569],
       [ 1.43270697, -0.3126519 ],
       [-0.72058873,  0.88716294],
       [ 0.85958841, -0.6365235 ],
       [ 0.01569637, -2.24268495]])

In [228]:
first, two, t = np.split(arr, [1, 3], axis=0)

In [229]:
first

array([[ 0.47143516, -1.19097569]])

In [230]:
two

array([[ 1.43270697, -0.3126519 ],
       [-0.72058873,  0.88716294]])

In [231]:
t

array([[ 0.85958841, -0.6365235 ],
       [ 0.01569637, -2.24268495]])

In [250]:
X = np.random.rand(5, 10)

In [251]:
X.mean()

0.5198956550284803

In [252]:
Y = X - X.mean(axis=1, keepdims=True)

In [253]:
Y

array([[-0.01942625,  0.51093009, -0.34713195, -0.35169376,  0.2674484 ,
         0.11622898,  0.00055788, -0.36394784, -0.24185609,  0.42889054],
       [-0.05407282,  0.0650253 , -0.46461785, -0.17018466, -0.03393319,
         0.14132264,  0.44737171,  0.15491031,  0.2351712 , -0.32099265],
       [ 0.16279739,  0.24774097,  0.05045975, -0.14495614, -0.43069325,
        -0.01485641, -0.05504174,  0.36816274, -0.10290684, -0.08070646],
       [-0.06566891,  0.21665496, -0.54543147,  0.06687464,  0.16456952,
         0.10556825,  0.19432008, -0.04478628,  0.36328942, -0.45539021],
       [-0.44211713,  0.12212936, -0.35769843,  0.47904572, -0.14605671,
        -0.27814544, -0.01395248,  0.44863844,  0.40730503, -0.21914837]])

In [254]:
Y.mean()

3.3306690738754695e-17

In [235]:
x = np.random.rand(2, 2)

In [236]:
x

array([[0.4780938 , 0.19567518],
       [0.38231745, 0.05387369]])

In [237]:
x - np.array([1, 2])

array([[-0.5219062 , -1.80432482],
       [-0.61768255, -1.94612631]])

In [238]:
0.47 -1

-0.53

In [239]:
0.38 - 1

-0.62

In [282]:
def m(area=5):
    Z = np.zeros((area,area), [('x',float),('y',float)])
    Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,area),
                                 np.linspace(0,1,area))
    return Z

In [299]:
m(10)

array([[(0.        , 0.        ), (0.11111111, 0.        ),
        (0.22222222, 0.        ), (0.33333333, 0.        ),
        (0.44444444, 0.        ), (0.55555556, 0.        ),
        (0.66666667, 0.        ), (0.77777778, 0.        ),
        (0.88888889, 0.        ), (1.        , 0.        )],
       [(0.        , 0.11111111), (0.11111111, 0.11111111),
        (0.22222222, 0.11111111), (0.33333333, 0.11111111),
        (0.44444444, 0.11111111), (0.55555556, 0.11111111),
        (0.66666667, 0.11111111), (0.77777778, 0.11111111),
        (0.88888889, 0.11111111), (1.        , 0.11111111)],
       [(0.        , 0.22222222), (0.11111111, 0.22222222),
        (0.22222222, 0.22222222), (0.33333333, 0.22222222),
        (0.44444444, 0.22222222), (0.55555556, 0.22222222),
        (0.66666667, 0.22222222), (0.77777778, 0.22222222),
        (0.88888889, 0.22222222), (1.        , 0.22222222)],
       [(0.        , 0.33333333), (0.11111111, 0.33333333),
        (0.22222222, 0.33333333), (0.

In [286]:
Z = np.zeros((4, 4), [('x', float), ('y', float)])

In [293]:
Z['x'], Z['y'] = np.meshgrid(np.linspace(0, 1, 4),
                             np.linspace(0, 1, 4))

In [296]:
Z

array([[(0.        , 0.        ), (0.33333333, 0.        ),
        (0.66666667, 0.        ), (1.        , 0.        )],
       [(0.        , 0.33333333), (0.33333333, 0.33333333),
        (0.66666667, 0.33333333), (1.        , 0.33333333)],
       [(0.        , 0.66666667), (0.33333333, 0.66666667),
        (0.66666667, 0.66666667), (1.        , 0.66666667)],
       [(0.        , 1.        ), (0.33333333, 1.        ),
        (0.66666667, 1.        ), (1.        , 1.        )]],
      dtype=[('x', '<f8'), ('y', '<f8')])

In [295]:
Z['y']

array([[0.        , 0.        , 0.        , 0.        ],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.66666667, 0.66666667, 0.66666667, 0.66666667],
       [1.        , 1.        , 1.        , 1.        ]])

In [279]:
# Moving Average
def moving_average(a, window=5):
        
    ret = np.cumsum(a)
    ret[window: ] = ret[window: ] - ret[: -window]
    return ret[window-1:] / window

Z = np.random.randn(100)
print(Z)
print(moving_average(Z, 50))

[-1.33674210e-01 -1.07740332e+00  1.24990251e+00  5.71148753e-01
  2.97048429e-01  8.71865218e-01 -1.63711197e-01  6.89523199e-01
  1.98458990e+00 -1.18281885e-01  9.55129919e-01 -1.18055289e+00
  1.47047394e+00 -2.15578836e-02  7.10861471e-01 -8.11835052e-01
 -2.25121307e+00 -1.12610019e+00 -3.07866746e-01 -9.61884536e-01
  6.70825959e-01  6.33834266e-02 -6.56795880e-01 -2.88363182e-01
 -2.19793496e-01  2.00247961e-01 -8.45500241e-01  2.64292268e+00
 -3.33744771e-01 -1.45508360e-01  8.93368708e-01  1.28855474e+00
  3.31198188e-01 -7.53678981e-02 -6.11476555e-02  1.85605687e+00
 -7.53041282e-01 -3.40225870e-01 -5.50996039e-01 -6.04037326e-01
  2.12258996e+00  2.03055207e-02 -8.66260054e-01 -3.55888386e-01
 -9.54342311e-01  1.59146411e+00  5.87338037e-04 -4.64031732e-01
 -1.52371079e+00  1.54870365e-01 -8.40649344e-01  1.06857825e-02
 -5.43740390e-01  6.75455344e-01 -9.73342213e-01  8.18348102e-01
 -1.16017285e-01 -6.90858214e-01  1.03895548e+00  9.81271848e-01
  6.16620804e-01 -7.87487

In [257]:
window = 5

In [271]:
ret[window:] = ret[window:] - ret[:-window]

In [272]:
ret[window - 1:] / window

array([-0.30914364, -0.48111008, -0.05927566, -0.15366114, -0.13458799,
       -0.15161206,  0.3448309 ,  0.2908972 ,  0.55181139,  0.5474536 ,
        0.74186693,  0.78127207,  0.91566463,  1.01612929,  1.27524947,
        0.93135624,  0.59785249,  0.44366137,  0.18525105,  0.42032079,
        0.63766589,  0.72776561,  0.63524388,  0.27484953, -0.18763438,
       -0.28729658, -0.24017241, -0.23602271,  0.20393523,  0.34130926,
        0.32731083, -0.04606014, -0.34501307, -0.31935639, -0.26293851,
        0.32125013,  0.54920903,  0.93243724,  0.82739146,  0.81127337,
        0.43111753,  0.14092687, -0.27118158,  0.01475761,  0.15104985,
        0.05671117,  0.09082733,  0.42825413,  0.5702299 , -0.00861371,
       -0.36830491, -0.16673925, -0.22500327, -0.85156234, -0.67687614,
       -0.28467498, -0.41083976, -0.56927977, -0.00960078,  0.19925878,
        0.15107715,  0.42518984,  0.64269198,  0.55211997,  0.58366447,
        0.89979781,  0.62934312,  0.64706391,  0.4364673 ,  0.23

In [273]:
ret

array([ 0.28837685, -0.76316209, -1.08272349, -1.70271658, -1.5457182 ,
       -2.4055504 , -0.29637828, -0.76830569, -0.67293995, -0.75806028,
        1.72415449,  1.45448599,  2.75905695,  2.73726801,  3.70933463,
        3.90636036,  4.57832315,  5.08064647,  6.37624735,  4.65678121,
        2.98926245,  2.21830683,  0.92625524,  2.10160396,  3.18832946,
        3.63882803,  3.1762194 ,  1.37424763, -0.93817192, -1.43648291,
       -1.20086205, -1.18011356,  1.01967614,  1.70654631,  1.63655414,
       -0.2303007 , -1.72506534, -1.59678193, -1.31469255,  1.60625067,
        2.74604513,  4.66218622,  4.13695728,  4.05636686,  2.15558764,
        0.70463434, -1.3559079 ,  0.07378806,  0.75524927,  0.28355586,
        0.45413663,  2.14127066,  2.85114948, -0.04306855, -1.84152454,
       -0.83369626, -1.12501637, -4.25781169, -3.38438069, -1.42337489,
       -2.0541988 , -2.84639883, -0.0480039 ,  0.99629388,  0.75538575,
        2.12594919,  3.2134599 ,  2.76059987,  2.91832236,  4.49

In [280]:
ret = np.cumsum(np.array([1, 2, 3, 4, 5, 6, 7, 8]))

In [281]:
ret

array([ 1,  3,  6, 10, 15, 21, 28, 36])

In [270]:
Z

array([ 0.28837685, -1.05153894, -0.3195614 , -0.61999309,  0.15699838,
       -0.57145535,  1.05763318, -0.79148881, -0.52462735,  0.07187804,
        1.91075943,  0.78796468,  0.51308214, -0.54641628,  1.04394466,
        2.10778515,  1.45992748,  1.01540546,  0.7491846 , -0.67552148,
        0.44026639,  0.68897186, -0.27664613,  1.92453332,  0.41120402,
        0.89076496,  0.22636323, -2.07861789, -0.38788623, -0.08710697,
        1.12638582,  0.24711172,  0.12117181,  0.29898394, -0.15709914,
       -0.74046902, -1.24765292,  0.24945522,  0.58107332,  2.76384408,
        0.39932544,  0.66848817, -0.27577373,  0.5004829 ,  0.86306486,
       -1.05162786, -1.39205408,  1.15392224,  1.18194411,  0.39137145,
       -0.88104709,  0.29507996,  1.86380106, -1.71227392, -1.40708455,
        0.12678119,  0.00375985, -1.26899426, -0.83884292,  0.55392125,
       -0.50404272, -0.78844018,  1.52940067,  0.20545485,  0.31301313,
        0.86652071,  0.29907053,  1.07654064,  0.36317735,  1.89