# PANDAS

In [2]:
import pandas as pd
import numpy as np

In [3]:
obj = pd.Series([4, 7, -5, 3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3])

In [7]:
list(obj.index)

[0, 1, 2, 3]

In [8]:
obj2 = pd.Series([4, 7, -5, 3], index=['Enero', 'Febrero', 'Marzo', 'Abril'])

In [14]:
obj2.values

array([ 4,  7, -5,  3])

In [17]:
obj2['Septiembre']

KeyError: 'Septiembre'

In [25]:
obj2[obj2 > 2]

Enero      4
Febrero    7
Abril      3
dtype: int64

In [27]:
obj2 ** 2

Enero      16
Febrero    49
Marzo      25
Abril       9
dtype: int64

In [28]:
np.exp(obj2)

Enero        54.598150
Febrero    1096.633158
Marzo         0.006738
Abril        20.085537
dtype: float64

In [29]:
d = {'Enero': 3, 'Febrero': 4}

In [30]:
'Enero' in d

True

In [32]:
'Enero' in obj2.index

True

In [33]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [37]:
# No es lo mismo que lo de la celda de abajo
pop = pd.Series(data=sdata.values(), index=sdata.keys())
pop

In [53]:
pop1 = pd.Series(data=sdata)

In [40]:
pop

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [41]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [54]:
pop2 = pd.Series(data=sdata, index=states)

In [45]:
pop.notnull()

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [50]:
np.sum(pop.isnull()) / pop.shape[0]

0.25

In [51]:
pop[pop.notnull()]

Ohio      35000.0
Oregon    16000.0
Texas     71000.0
dtype: float64

In [52]:
pop[~pop.isnull()] # Exactamente lo mismo que lo que hay qrriba

Ohio      35000.0
Oregon    16000.0
Texas     71000.0
dtype: float64

In [58]:
pt = pop1 + pop2

In [56]:
pop1

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [57]:
pop2

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [61]:
pt.isna()

California     True
Ohio          False
Oregon        False
Texas         False
Utah           True
dtype: bool

In [63]:
pt.name = 'total population'

In [65]:
pt.index.name = 'State'

In [66]:
pt

State
California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
Name: total population, dtype: float64

In [68]:
pt.index[0] = 'Bob'

TypeError: Index does not support mutable operations

In [72]:
pt.index = ['a', 'b', 'c', 'd', 'e']

In [73]:
pt

a         NaN
b     70000.0
c     32000.0
d    142000.0
e         NaN
Name: total population, dtype: float64

In [75]:
datos = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9]}

In [76]:
df = pd.DataFrame(data=datos)

In [78]:
matrix = np.random.randn(5, 5)

In [80]:
df2 = pd.DataFrame(data=matrix, columns=['Temp', 'Viento', 'Presion', 'Lluvia', 'X'])

In [82]:
df2.index

RangeIndex(start=0, stop=5, step=1)

In [83]:
df2.values

array([[-0.1601935 , -1.0756715 , -0.96313978, -1.25418383, -0.77355999],
       [ 0.67708984,  1.22051759,  0.12268732, -0.27956731,  0.11888452],
       [ 1.55941441,  0.73937313, -0.60305875, -1.09896692, -0.19043294],
       [-0.35881144,  0.32440031,  1.67121412,  0.49736604, -1.25162178],
       [-0.62470955, -0.46237661, -0.59219872,  0.30307926,  0.64192124]])

In [198]:
df3 = pd.DataFrame(data=matrix, columns=['shape', 'Viento', 'Presion', 'Lluvia', 'X'], 
                   index=[2001, 2002, 2003, 2004, 2005])

In [199]:
df3

shape    Viento   Presion    Lluvia         X
2001 -0.160193 -1.075671 -0.963140 -1.254184 -0.773560
2002  0.677090  1.220518  0.122687 -0.279567  0.118885
2003  1.559414  0.739373 -0.603059 -1.098967 -0.190433
2004 -0.358811  0.324400  1.671214  0.497366 -1.251622
2005 -0.624710 -0.462377 -0.592199  0.303079  0.641921

In [200]:
df3.columns

Index(['shape', 'Viento', 'Presion', 'Lluvia', 'X'], dtype='object')

In [201]:
df3

shape    Viento   Presion    Lluvia         X
2001 -0.160193 -1.075671 -0.963140 -1.254184 -0.773560
2002  0.677090  1.220518  0.122687 -0.279567  0.118885
2003  1.559414  0.739373 -0.603059 -1.098967 -0.190433
2004 -0.358811  0.324400  1.671214  0.497366 -1.251622
2005 -0.624710 -0.462377 -0.592199  0.303079  0.641921

In [202]:
for col in df3.columns:
    print(col)

shape
Viento
Presion
Lluvia
X


In [203]:
df3.shape

(5, 5)

In [204]:
df3['shape']

2001   -0.160193
2002    0.677090
2003    1.559414
2004   -0.358811
2005   -0.624710
Name: shape, dtype: float64

In [205]:
df3[['shape', 'Viento']]

shape    Viento
2001 -0.160193 -1.075671
2002  0.677090  1.220518
2003  1.559414  0.739373
2004 -0.358811  0.324400
2005 -0.624710 -0.462377

SELECT shape, Viento FROM df3;

In [206]:
df3.loc[2003]

shape      1.559414
Viento     0.739373
Presion   -0.603059
Lluvia    -1.098967
X         -0.190433
Name: 2003, dtype: float64

In [207]:
df3

shape    Viento   Presion    Lluvia         X
2001 -0.160193 -1.075671 -0.963140 -1.254184 -0.773560
2002  0.677090  1.220518  0.122687 -0.279567  0.118885
2003  1.559414  0.739373 -0.603059 -1.098967 -0.190433
2004 -0.358811  0.324400  1.671214  0.497366 -1.251622
2005 -0.624710 -0.462377 -0.592199  0.303079  0.641921

In [208]:
df3['Rocio'] = np.random.rand(5)

In [209]:
df3['cte'] = 0

In [210]:
df3

shape    Viento   Presion    Lluvia         X     Rocio  cte
2001 -0.160193 -1.075671 -0.963140 -1.254184 -0.773560  0.510191    0
2002  0.677090  1.220518  0.122687 -0.279567  0.118885  0.455368    0
2003  1.559414  0.739373 -0.603059 -1.098967 -0.190433  0.468160    0
2004 -0.358811  0.324400  1.671214  0.497366 -1.251622  0.694898    0
2005 -0.624710 -0.462377 -0.592199  0.303079  0.641921  0.442644    0

In [211]:
df_aux = df3.copy() # <-- Copy para evitar que los cambios en un auxiliar se propagen al df inicial
del df_aux['cte']
df_aux

shape    Viento   Presion    Lluvia         X     Rocio
2001 -0.160193 -1.075671 -0.963140 -1.254184 -0.773560  0.510191
2002  0.677090  1.220518  0.122687 -0.279567  0.118885  0.455368
2003  1.559414  0.739373 -0.603059 -1.098967 -0.190433  0.468160
2004 -0.358811  0.324400  1.671214  0.497366 -1.251622  0.694898
2005 -0.624710 -0.462377 -0.592199  0.303079  0.641921  0.442644

In [212]:
df3

shape    Viento   Presion    Lluvia         X     Rocio  cte
2001 -0.160193 -1.075671 -0.963140 -1.254184 -0.773560  0.510191    0
2002  0.677090  1.220518  0.122687 -0.279567  0.118885  0.455368    0
2003  1.559414  0.739373 -0.603059 -1.098967 -0.190433  0.468160    0
2004 -0.358811  0.324400  1.671214  0.497366 -1.251622  0.694898    0
2005 -0.624710 -0.462377 -0.592199  0.303079  0.641921  0.442644    0

In [213]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

In [214]:
pop.get('Nevada')

{2001: 2.4, 2002: 2.9}

In [215]:
popu = pd.DataFrame(pop)

In [216]:
transpose = popu.T

In [217]:
transpose.values

array([[2.4, 2.9, nan],
       [1.7, 3.6, 1.5]])

In [218]:
transpose[2001].values

array([2.4, 1.7])

In [219]:
transpose.index

Index(['Nevada', 'Ohio'], dtype='object')

In [220]:
idx = pd.MultiIndex.from_arrays([[1, 1, 2, 2], ['red', 'blue', 'red', 'blue']], names=('number', 'color'))

In [221]:
mi = pd.DataFrame(index=idx, data=[1, 3, 6 ,7], columns=['goles'])

In [222]:
mi.loc[(1, 'red')]

goles    1
Name: (1, red), dtype: int64

In [223]:
pd.DataFrame(['hello', 'world'], index=idx, columns=['HW'])

ValueError: Shape of passed values is (2, 1), indices imply (4, 1)

In [224]:
df3.reindex([2003, 2004, 2005, 2006, 2007], fill_value=np.mean(df3.values))

shape    Viento   Presion    Lluvia         X     Rocio       cte
2003  1.559414  0.739373 -0.603059 -1.098967 -0.190433  0.468160  0.000000
2004 -0.358811  0.324400  1.671214  0.497366 -1.251622  0.694898  0.000000
2005 -0.624710 -0.462377 -0.592199  0.303079  0.641921  0.442644  0.000000
2006  0.021678  0.021678  0.021678  0.021678  0.021678  0.021678  0.021678
2007  0.021678  0.021678  0.021678  0.021678  0.021678  0.021678  0.021678

In [225]:
df3

shape    Viento   Presion    Lluvia         X     Rocio  cte
2001 -0.160193 -1.075671 -0.963140 -1.254184 -0.773560  0.510191    0
2002  0.677090  1.220518  0.122687 -0.279567  0.118885  0.455368    0
2003  1.559414  0.739373 -0.603059 -1.098967 -0.190433  0.468160    0
2004 -0.358811  0.324400  1.671214  0.497366 -1.251622  0.694898    0
2005 -0.624710 -0.462377 -0.592199  0.303079  0.641921  0.442644    0

In [226]:
np.mean(df3.values, axis=0)

array([ 0.21855795,  0.14924858, -0.07289916, -0.36645455, -0.29096179,
        0.51425213,  0.        ])

In [227]:
df2 = df3.drop('shape', axis=1, )

In [228]:
df2

Viento   Presion    Lluvia         X     Rocio  cte
2001 -1.075671 -0.963140 -1.254184 -0.773560  0.510191    0
2002  1.220518  0.122687 -0.279567  0.118885  0.455368    0
2003  0.739373 -0.603059 -1.098967 -0.190433  0.468160    0
2004  0.324400  1.671214  0.497366 -1.251622  0.694898    0
2005 -0.462377 -0.592199  0.303079  0.641921  0.442644    0

In [229]:
df3

shape    Viento   Presion    Lluvia         X     Rocio  cte
2001 -0.160193 -1.075671 -0.963140 -1.254184 -0.773560  0.510191    0
2002  0.677090  1.220518  0.122687 -0.279567  0.118885  0.455368    0
2003  1.559414  0.739373 -0.603059 -1.098967 -0.190433  0.468160    0
2004 -0.358811  0.324400  1.671214  0.497366 -1.251622  0.694898    0
2005 -0.624710 -0.462377 -0.592199  0.303079  0.641921  0.442644    0

In [230]:
df3.drop('shape', axis=1, inplace=True)

In [231]:
df3

Viento   Presion    Lluvia         X     Rocio  cte
2001 -1.075671 -0.963140 -1.254184 -0.773560  0.510191    0
2002  1.220518  0.122687 -0.279567  0.118885  0.455368    0
2003  0.739373 -0.603059 -1.098967 -0.190433  0.468160    0
2004  0.324400  1.671214  0.497366 -1.251622  0.694898    0
2005 -0.462377 -0.592199  0.303079  0.641921  0.442644    0

In [232]:
df3.drop('Lluvia', axis=1, inplace=True) # Esta linea hace lo mismo que la de abajo
df3 = df3.drop('Lluvia', axis=1)

KeyError: "['Lluvia'] not found in axis"

In [233]:
df3[~(df3['Presion'] < 0)]

Viento   Presion         X     Rocio  cte
2002  1.220518  0.122687  0.118885  0.455368    0
2004  0.324400  1.671214 -1.251622  0.694898    0

In [234]:
# FILTRADO
df3[df3['year'] == 2003]

KeyError: 'year'

In [236]:
df3[df3['Rocio'] > 0]['Rocio'] = 0

# RECORDAR EL CAMBIAR UN VALOR TRAS FILTRADO

In [254]:
df3.loc[df3['outlier'] > 5%, 'outlier'] = np.mean(df3['col'].values)

In [255]:
df3

Viento   Presion         X  Rocio  cte  newnew
2001 -1.075671 -0.963140 -0.773560    0.0    0       4
2002  0.000000 -0.431679  0.118885    0.0    0       4
2003  0.000000 -0.603059 -0.190433    0.0    0       4
2004  0.000000 -0.431679 -1.251622    0.0    0       4
2005 -0.462377 -0.592199  0.641921    0.0    0       4

In [247]:
df3.loc[2001, 'Presion']

-0.9631397820080684

In [249]:
df3['newnew'] = 4

In [250]:
df3

Viento   Presion         X  Rocio  cte  newnew
2001 -1.075671 -0.963140 -0.773560    0.0    0       4
2002  0.000000  0.122687  0.118885    0.0    0       4
2003  0.000000 -0.603059 -0.190433    0.0    0       4
2004  0.000000  1.671214 -1.251622    0.0    0       4
2005 -0.462377 -0.592199  0.641921    0.0    0       4

In [259]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [260]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [261]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [262]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [263]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [264]:
s1*s2

a   -15.33
c    -9.00
d      NaN
e    -2.25
f      NaN
g      NaN
dtype: float64

In [276]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'),
                index=['Ohio', 'Texas', 'Colorado'])

df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
               index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [279]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [280]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [278]:
df1.add(df2, fill_value=0)

b    c     d     e
Colorado  6.0  7.0   8.0   NaN
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  NaN  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  NaN   1.0   2.0

In [277]:
df1 +df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [293]:
df = pd.DataFrame(data=np.random.randn(4, 4), columns=['ingresos', 'gastos', '3', '4'])

In [294]:
df

ingresos    gastos         3         4
0  0.460926 -1.289039  0.858115 -0.680781
1 -0.437952  0.872487  2.664445 -1.154677
2 -0.803696 -0.674203 -0.850991 -0.460753
3 -0.475034 -1.757513  0.077555 -0.797184

In [295]:
df['revenue'] = df['ingresos'] - df['gastos']

In [296]:
df

ingresos    gastos         3         4   revenue
0  0.460926 -1.289039  0.858115 -0.680781  1.749965
1 -0.437952  0.872487  2.664445 -1.154677 -1.310439
2 -0.803696 -0.674203 -0.850991 -0.460753 -0.129494
3 -0.475034 -1.757513  0.077555 -0.797184  1.282479

In [299]:
df -1 

ingresos    gastos         3         4   revenue
0 -0.539074 -2.289039 -0.141885 -1.680781  0.749965
1 -1.437952 -0.127513  1.664445 -2.154677 -2.310439
2 -1.803696 -1.674203 -1.850991 -1.460753 -1.129494
3 -1.475034 -2.757513 -0.922445 -1.797184  0.282479

In [289]:
discount = pd.Series(np.random.randn(4), index=['0', '1', '2', '3'])

In [290]:
discount

0    1.650849
1    1.525979
2    0.450888
3    0.979308
dtype: float64

In [292]:
df - df['3']

0   1   2   3   3   4  gastos  ingresos  revenue
0 NaN NaN NaN NaN NaN NaN     NaN       NaN      NaN
1 NaN NaN NaN NaN NaN NaN     NaN       NaN      NaN
2 NaN NaN NaN NaN NaN NaN     NaN       NaN      NaN
3 NaN NaN NaN NaN NaN NaN     NaN       NaN      NaN

In [288]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [303]:
df['ingresos'].mean()

-0.3139389613459975

In [307]:
df.median()

ingresos   -0.456493
gastos     -0.981621
3           0.467835
4          -0.738982
revenue     0.576493
dtype: float64

In [308]:
fl = lambda x: x.max() - x.min()
df.apply(f)

In [309]:
df.apply(fl)

ingresos    1.264622
gastos      2.630000
3           3.515436
4           0.693924
revenue     3.060403
dtype: float64

In [310]:
df

ingresos    gastos         3         4   revenue
0  0.460926 -1.289039  0.858115 -0.680781  1.749965
1 -0.437952  0.872487  2.664445 -1.154677 -1.310439
2 -0.803696 -0.674203 -0.850991 -0.460753 -0.129494
3 -0.475034 -1.757513  0.077555 -0.797184  1.282479

In [312]:
l = {}
for col in df.columns:
    l[col] = df[col].max()-df[col].min()
pd.Series(l)

In [313]:
l

{'ingresos': 1.2646216323926223,
 'gastos': 2.6300001786063354,
 '3': 3.5154361595863515,
 '4': 0.6939244181887538,
 'revenue': 3.060403343428452}

In [316]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

In [317]:
df.apply(f)

ingresos    gastos         3         4   revenue
min -0.803696 -1.757513 -0.850991 -1.154677 -1.310439
max  0.460926  0.872487  2.664445 -0.460753  1.749965

In [318]:
def normalized(x):
    return x.median() - x.mean()

In [319]:
df.apply(normalized)

ingresos   -0.142554
gastos     -0.269554
3          -0.219446
4           0.034366
revenue     0.178365
dtype: float64

In [320]:
def round_elements(x):
    return round(x, 2)

In [322]:
df_aux = df.applymap(round_elements).copy()

In [331]:
df_aux.index = ['Enero', 'Enero', 'Marzo', 'Abril']

In [335]:
df_aux.reset_index(inplace=True, drop=False)

In [336]:
df_aux

index  ingresos  gastos     3     4  revenue
0  Enero      0.46   -1.29  0.86 -0.68     1.75
1  Enero     -0.44    0.87  2.66 -1.15    -1.31
2  Marzo     -0.80   -0.67 -0.85 -0.46    -0.13
3  Abril     -0.48   -1.76  0.08 -0.80     1.28

In [337]:
df_aux.index.is_unique

True

In [341]:
df_aux['index'].nunique()

3

In [342]:
df_aux.loc[df_aux['3'] < 0, '3'] = np.nan

In [343]:
df_aux

index  ingresos  gastos     3     4  revenue
0  Enero      0.46   -1.29  0.86 -0.68     1.75
1  Enero     -0.44    0.87  2.66 -1.15    -1.31
2  Marzo     -0.80   -0.67   NaN -0.46    -0.13
3  Abril     -0.48   -1.76  0.08 -0.80     1.28

In [344]:
df_aux['3'].mean()

1.2

In [346]:
df_aux['3'].mean(skipna=True, )

1.2

In [350]:
df_aux['ingresos'].idxmax()

0

In [351]:
df_aux.describe()

ingresos    gastos         3         4   revenue
count  4.000000  4.000000  3.000000  4.000000  4.000000
mean  -0.315000 -0.712500  1.200000 -0.772500  0.397500
std    0.541202  1.145553  1.323178  0.288372  1.390668
min   -0.800000 -1.760000  0.080000 -1.150000 -1.310000
25%   -0.560000 -1.407500  0.470000 -0.887500 -0.425000
50%   -0.460000 -0.980000  0.860000 -0.740000  0.575000
75%   -0.215000 -0.285000  1.760000 -0.625000  1.397500
max    0.460000  0.870000  2.660000 -0.460000  1.750000

In [353]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [355]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [357]:
!pip install pandas-datareader

     |████████████████████████████████| 112kB 3.6MB/s eta 0:00:01


In [71]:
import pandas_datareader.data as web

In [72]:
import pandas as pd

In [73]:
all_data = {}
for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']:
    all_data[ticker] = web.get_data_yahoo(ticker)

price = pd.DataFrame({tic: data['Adj Close']
                   for tic, data in all_data.items()})
volume = pd.DataFrame({tic: data['Volume']
                    for tic, data in all_data.items()})

In [16]:
price.dtypes

AAPL    float64
IBM     float64
MSFT    float64
GOOG    float64
dtype: object

In [13]:
price.head()

AAPL         IBM       MSFT        GOOG
Date                                                     
2015-03-23  117.066200  132.212097  38.646210  557.279968
2015-03-24  116.587677  130.903015  38.682270  568.628845
2015-03-25  113.541618  127.851295  37.383846  557.255066
2015-03-26  114.333046  128.967529  37.158421  553.649963
2015-03-27  113.421997  128.815002  36.942028  546.838684

In [14]:
volume.head()

AAPL        IBM        MSFT       GOOG
Date                                                    
2015-03-23  37709700.0  5930100.0  26246100.0  1643800.0
2015-03-24  32842300.0  4346100.0  25513300.0  2583200.0
2015-03-25  51655200.0  5428900.0  43469900.0  2152200.0
2015-03-26  47572900.0  4396000.0  37495600.0  1572600.0
2015-03-27  39546200.0  3477900.0  34401400.0  1897400.0

In [19]:
volume.sort_index(ascending=False)

AAPL         IBM        MSFT       GOOG
Date                                                      
2020-03-20  100257000.0  10543400.0  84796500.0  3600300.0
2020-03-19   67964300.0   8396500.0  85922700.0  3651100.0
2020-03-18   75058400.0   8772500.0  81593200.0  4233400.0
2020-03-17   81014000.0   9258300.0  81059800.0  3861500.0
2020-03-16   80605900.0  10568000.0  87905900.0  4252400.0
...                 ...         ...         ...        ...
2015-03-27   39546200.0   3477900.0  34401400.0  1897400.0
2015-03-26   47572900.0   4396000.0  37495600.0  1572600.0
2015-03-25   51655200.0   5428900.0  43469900.0  2152200.0
2015-03-24   32842300.0   4346100.0  25513300.0  2583200.0
2015-03-23   37709700.0   5930100.0  26246100.0  1643800.0

[1259 rows x 4 columns]

In [40]:
returns = price.pct_change(periods=1)

In [43]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.499278  0.676624  0.614883
IBM   0.499278  1.000000  0.564311  0.494690
MSFT  0.676624  0.564311  1.000000  0.730204
GOOG  0.614883  0.494690  0.730204  1.000000

In [38]:
price.std()

AAPL     54.707429
IBM      11.083487
MSFT     36.676294
GOOG    237.081201
dtype: float64

In [45]:
returns.corrwith(volume)

AAPL   -0.158349
IBM    -0.119447
MSFT   -0.066657
GOOG   -0.051781
dtype: float64

In [48]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [51]:
obj.value_counts() / obj.count()

a    0.333333
c    0.333333
b    0.222222
d    0.111111
dtype: float64

In [50]:
obj.count()

9

In [54]:
obj.isin(['3', 'a'])

0    False
1     True
2    False
3     True
4     True
5    False
6    False
7    False
8    False
dtype: bool

In [58]:
import numpy as np

In [65]:
string_data = pd.Series(['aardvark', 'artichoke', np.nan, 'avocado', None])

In [66]:
string_data

0     aardvark
1    artichoke
2          NaN
3      avocado
4         None
dtype: object

In [68]:
string_data.isnull()

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [67]:
string_data[string_data.isnull()]

2     NaN
4    None
dtype: object

In [69]:
string_data.isna()

0    False
1    False
2     True
3    False
4     True
dtype: bool

In [70]:
string_data.dropna(inplace=True)

0     aardvark
1    artichoke
3      avocado
dtype: object

In [77]:
price.columns

Index(['AAPL', 'IBM', 'MSFT', 'GOOG'], dtype='object')

In [78]:
price.loc[price['AAPL'] > 200, 'AAPL'] = None

In [81]:
price['AAPL'].isnull().sum()

259

In [82]:
price.shape

(1258, 4)

In [83]:
259 / 1258

0.20588235294117646

In [92]:
price['AAPL'].mean()

135.8707299065423

In [95]:
price['AAPL'].fillna(method='bfill')

Date
2015-03-26    114.333046
2015-03-27    113.421997
2015-03-30    116.293190
2015-03-31    114.507881
2015-04-01    114.342239
                 ...    
2020-03-18           NaN
2020-03-19           NaN
2020-03-20           NaN
2020-03-23           NaN
2020-03-24           NaN
Name: AAPL, Length: 1258, dtype: float64

In [93]:
price['AAPL']

Date
2015-03-26    114.333046
2015-03-27    113.421997
2015-03-30    116.293190
2015-03-31    114.507881
2015-04-01    114.342239
                 ...    
2020-03-18           NaN
2020-03-19           NaN
2020-03-20           NaN
2020-03-23           NaN
2020-03-24           NaN
Name: AAPL, Length: 1258, dtype: float64

In [76]:
string_data.fillna()

ValueError: Must specify a fill 'value' or 'method'.

In [97]:
data = pd.Series(np.random.randn(10),
               index=[['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'd', 'd'],
                      [1, 2, 3, 1, 2, 3, 1, 2, 2, 3]])

In [99]:
data = data.to_frame()

In [106]:
data.rename(columns={0: 'random'}, inplace=True)

In [112]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 2),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

In [116]:
stacked = data.unstack(level=0, fill_value=0)

In [114]:
data.unstack()

random                    
          1         2         3
a -1.640181  0.408119  0.159829
b -0.397150 -1.041728  0.467801
c -1.366851  1.525792       NaN
d       NaN  1.367368 -0.638544

In [115]:
data

random
a 1 -1.640181
  2  0.408119
  3  0.159829
b 1 -0.397150
  2 -1.041728
  3  0.467801
c 1 -1.366851
  2  1.525792
d 2  1.367368
  3 -0.638544

In [117]:
stacked.stack()

random
1 a -1.640181
  b -0.397150
  c -1.366851
  d  0.000000
2 a  0.408119
  b -1.041728
  c  1.525792
  d  1.367368
3 a  0.159829
  b  0.467801
  c  0.000000
  d -0.638544

In [118]:
stacked

random                              
          a         b         c         d
1 -1.640181 -0.397150 -1.366851  0.000000
2  0.408119 -1.041728  1.525792  1.367368
3  0.159829  0.467801  0.000000 -0.638544

In [119]:
pd.DataFrame({'España': [4e6, 54, 10], 'Alemania': [5e6, 45, 11]})

España   Alemania
0  4000000.0  5000000.0
1       54.0       45.0
2       10.0       11.0

In [120]:
pd.DataFrame({'country':['españa', 'alemania'], 'pob': [4e6, 5e6], 'edad': [54, 45]})

country        pob  edad
0    españa  4000000.0    54
1  alemania  5000000.0    45

In [122]:
df1 = pd.DataFrame({'key': ['b', 'b', 'a', 'c', 'a', 'a', 'b'],
                'data1': range(7)})

In [124]:
df2 = pd.DataFrame({'key': ['a', 'b', 'd'],
                 'data2': range(3)})

In [125]:
df1

key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [133]:
df2.rename(columns={'key': 'clave', 'data2': 'data1'}, inplace=True)

In [134]:
df2

clave  data1
0     a      0
1     b      1
2     d      2

In [128]:
df_merged = pd.merge(left=df1, right=df2, how='left', on=['key'])

In [129]:
df_merged

key  data1  data2
0   b      0    1.0
1   b      1    1.0
2   a      2    0.0
3   c      3    NaN
4   a      4    0.0
5   a      5    0.0
6   b      6    1.0

In [132]:
pd.merge(left=df1, right=df2, how='left', left_on=['key'], right_on=['clave'])

key  data1 clave  data2
0   b      0     b    1.0
1   b      1     b    1.0
2   a      2     a    0.0
3   c      3   NaN    NaN
4   a      4     a    0.0
5   a      5     a    0.0
6   b      6     b    1.0

In [136]:
pd.merge(left=df1, right=df2, how='left', left_on=['key'], right_on=['clave'], suffixes=('_df1', '_df2'), )

key  data1_df1 clave  data1_df2
0   b          0     b        1.0
1   b          1     b        1.0
2   a          2     a        0.0
3   c          3   NaN        NaN
4   a          4     a        0.0
5   a          5     a        0.0
6   b          6     b        1.0

In [137]:
s1 = pd.Series([0, 1], index=['a', 'b'])

In [145]:
s2 = pd.Series([2, 3, 4], index=['a', 'd', 'e'])

In [139]:
s3 = pd.Series([5, 6], index=['f', 'g'])

In [140]:
s1

a    0
b    1
dtype: int64

In [141]:
s2

c    2
d    3
e    4
dtype: int64

In [142]:
s3

f    5
g    6
dtype: int64

In [146]:
pd.concat([s1, s2, s3], axis=1, )

/Users/estebansanchez/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1    2
a  0.0  2.0  NaN
b  1.0  NaN  NaN
d  NaN  3.0  NaN
e  NaN  4.0  NaN
f  NaN  NaN  5.0
g  NaN  NaN  6.0

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/macrodatabook.csv')

FileNotFoundError: [Errno 2] File b'data/macrodatabook.csv' does not exist: b'data/macrodatabook.csv'